#!/usr/bin/env node
// Bundles each top-level slash-command script into a single self-contained JS
// file under dist/. Runtime dependencies (execa, zod, nanoid, yargs-parser)
// are inlined, so the published plugin has zero node_modules requirement —
// Claude Code can `/plugin install` and the commands run immediately.
import { build } from 'esbuild';
import { rmSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

const here = new URL('.', import.meta.url).pathname;
const entryDir = join(here, 'scripts');
const outDir = join(here, 'dist');

// Wipe stale output.
rmSync(outDir, { recursive: true, force: true });

const entryPoints = readdirSync(entryDir)
  .filter((f) => f.endsWith('.ts') && statSync(join(entryDir, f)).isFile())
  .map((f) => join(entryDir, f));

await build({
  entryPoints,
  outdir: outDir,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node18.18',
  // Each dep gets inlined into its entry's bundle. Node built-ins (node:fs,
  // node:child_process, …) are NOT bundled — they come from Node itself.
  packages: 'bundle',
  banner: {
    // ESM bundles cannot `require()` natively, but several deps (cross-spawn
    // inside execa, etc.) rely on dynamic requires. Shim a real `require` via
    // Node's createRequire so those paths resolve at runtime.
    js: [
      '// Auto-generated by build.mjs — do not edit.',
      "import { createRequire as __createRequire } from 'node:module';",
      'const require = __createRequire(import.meta.url);',
    ].join('\n'),
  },
  logLevel: 'info',
  // A few deps (e.g. execa) use dynamic requires for internal optimisations;
  // esbuild warns but bundles them anyway.
  legalComments: 'none',
});
